#! /usr/bin/env python

#-----------------------------------------
#  Demo loading a TaharezLayout (Demo8.LAYOUT from gui\datafiles\layouts)
#
#  Same comments on :  
#	 adding list items from within an event, cant see anyother way of doing it
#	 Events still dont appear to be returning window etc
#----------------------------------------

import os
from pyogre import ogre,cegui
import Framework

def _PointHack(x, y):
	return cegui.Vector2(x, y)
cegui.Point = _PointHack

class CEGUIFrameListener(Framework.FrameListener):
	def __init__(self, renderWindow, camera, sceneManager):
		Framework.FrameListener.__init__(self, renderWindow, camera)
		self.keepRendering = True   # whether to continue rendering or not
		self.sceneDetailIndex = 0

	def _setupInput(self):
		self.eventProcessor = ogre.EventProcessor()
		self.eventProcessor.initialise(self.renderWindow)
		self.eventProcessor.startProcessingEvents()

		# register as a listener for events
		self.eventProcessor.addKeyListener(self)
		self.eventProcessor.addMouseListener(self)
		self.eventProcessor.addMouseMotionListener(self)

	def frameStarted(self, evt):
		return self.keepRendering

	def mouseDragged(self, evt):
		self.mouseMoved(evt)

	def mousePressed(self, evt):
		button = self._convertOgreButtonToCegui(evt)
		cegui.System.getSingleton().injectMouseButtonDown(button)

	def mouseReleased(self, evt):
		button = self._convertOgreButtonToCegui(evt)
		cegui.System.getSingleton().injectMouseButtonUp(button)
		
	def mouseClicked(self, evt):
		pass

	def mouseEntered(self, evt):
		pass

	def mouseExited(self, evt):
		pass

	def mouseMoved(self, evt):
		system = cegui.System.getSingleton()
		renderer = system.renderer
		system.injectMouseMove(evt.relX * renderer.width,
							   evt.relY * renderer.height)

	def keyPressed(self, evt):
		if evt.key == ogre.KC_ESCAPE:
			self.keepRendering = False
		if evt.key == ogre.KC_SYSRQ:
			path, next = 'screenshot.png', 1
			while os.path.exists(path):
				path = 'screenshot_%d.png' % next
				next += 1
			
			self.renderWindow.writeContentsToFile(path)
			self.renderWindow.debugText = 'screenshot taken: ' + path
		if evt.key == ogre.KC_SCROLL:
			detailsLevel = ("SDL_SOLID", "SDL_WIREFRAME", "SDL_POINTS")
			self.sceneDetailIndex += 1 
			self.sceneDetailIndex %= len(detailsLevel)
			
			mode = detailsLevel[self.sceneDetailIndex]
			self.camera.detailLevel = getattr(ogre, mode)
			self.renderWindow.debugText = 'render mode set to: ' + mode

		system = cegui.System.getSingleton()
		system.injectKeyDown(evt.key)
		system.injectChar(evt.keyChar)
		evt.consume()

	def keyReleased(self, evt):
		system = cegui.System.getSingleton()
		system.injectKeyUp(evt.key)

	def keyClicked(self, evt):
		pass

	def _convertOgreButtonToCegui(self,evt):
		# Convert ogre button to cegui button
		if (evt.buttonID & ogre.MouseEvent.BUTTON0_MASK):
			print "Left Button"
			return cegui.LeftButton		
		elif (evt.buttonID & ogre.MouseEvent.BUTTON1_MASK):
			return cegui.RightButton		
		elif (evt.buttonID & ogre.MouseEvent.BUTTON2_MASK):
			return cegui.MiddleButton
		elif (evt.buttonID & ogre.MouseEvent.BUTTON3_MASK):
			return cegui.X1Button
		return cegui.LeftButton

class GEUIApplication(Framework.Application):
	def __init__(self):
		Framework.Application.__init__(self)
		self.guiRenderer=0
		self.system =0

	def _createGUI(self):
		# Initiaslise CEGUI Renderer
		self.guiRenderer = cegui.OgreCEGUIRenderer(self.renderWindow)
		self.system = cegui.System(self.guiRenderer)
		cegui.Logger.getSingleton().loggingLevel = cegui.Insane

		# Load Cegui Scheme
		cegui.SchemeManager.getSingleton().loadScheme("TaharezLook.scheme")
		self.system.defaultMouseCursor = "TaharezLook", "MouseArrow"
		cegui.FontManager.getSingleton().createFont("Tahoma.font")

		wmgr = cegui.WindowManager.getSingleton()
		root = wmgr.createWindow("DefaultWindow", "root")
		self.system.guiSheet = root

		login = cegui.WindowManager.getSingleton().loadWindowLayout("login.layout")
		self.system.guiSheet = login

		self.sceneManager.setSkyBox(True, 'skybox/SpaceSkyBox')

#		# Load Layout (from media/gui/datafiles/layout)
#		sheet = cegui.WindowManager.getSingleton().loadWindowLayout("Demo8.layout")
#		self.system.guiSheet = sheet
#
#		# Get controls
#		addButton = cegui.WindowManager.getSingleton().getWindow("Demo8/Window1/Controls/Add")
#		redScroll = cegui.WindowManager.getSingleton().getWindow("Demo8/Window1/Controls/Red")
#		greenScroll = cegui.WindowManager.getSingleton().getWindow("Demo8/Window1/Controls/Green")
#		blueScroll = cegui.WindowManager.getSingleton().getWindow("Demo8/Window1/Controls/Blue")
#		
#		# Info Panel
#		cegui.WindowManager.getSingleton().getWindow("Demo8/Window2/Info").text="An example of Text"
#
#		# Tips Window
#		cegui.WindowManager.getSingleton().getWindow("Demo8/Window2/Tips").text="Some Coloured Text"
#
#		# Events
#		ec= addButton.subscribeEvent(addButton.EventClicked, onAdd)
#		ec2= redScroll.subscribeEvent(redScroll.EventThumbTrackEnded, onScrollUpdate)
#		ec3= greenScroll.subscribeEvent(greenScroll.EventThumbTrackEnded, onScrollUpdate)
#		ec4= blueScroll.subscribeEvent(blueScroll.EventThumbTrackEnded, onScrollUpdate)
		
	def _createScene(self):
		sceneManager = self.sceneManager
		sceneManager.ambientLight = 0.25, 0.25, 0.25
		self._createGUI()


	def _createCamera(self):
		self.camera = self.sceneManager.createCamera("PlayerCam")
		self.camera.nearClipDistance = 5

	def _createFrameListener(self):
		self.frameListener = CEGUIFrameListener(self.renderWindow, self.camera, self.sceneManager)
		self.root.addFrameListener(self.frameListener)
		self.frameListener.showDebugOverlay(True)

	def __del__(self):
		"Clear variables, this is needed to ensure the correct order of deletion"
		del self.camera
		del self.sceneManager
		del self.frameListener
		del self.system
		del self.guiRenderer
		del self.root
		del self.renderWindow		
	 

if __name__ == '__main__':
	try:
		ta = GEUIApplication()
		ta.go()
	except ogre.OgreException, e:
		print e
