#! /bin/sh

ARGS=""
for ARG in "$@"; do
	ARGS="$ARGS \"$ARG\""
done

echo "The client is installed in $$CODEPATH$$"
export TPCLIENT_MEDIA=$$MEDIAPATH$$
export TPCLIENT_WINDOW=$$WINDOWPATH$$
export TPCLIENT_DOC=$$DOCPATH$$
echo "Media files are installed in $TPCLIENT_MEDIA"
echo "Window layout files are installed in $TPCLIENT_WINDOW"
echo "Documents   are installed in $TPCLIENT_DOC"

cd $$CODEPATH$$
$$CODEPATH$$/tpclient-pyogre $ARGS
