#! /bin/sh

for i in flares/*.png; do
	FILE=`basename $i`
	MATERIAL=`basename $FILE .png`
	
	cat > $MATERIAL.material <<EOF
// Light effects
material Billboards/Flares/$MATERIAL
{
  technique
  {
    pass
    {
      lighting off
      scene_blend add
      depth_write off
      texture_unit
      {
        texture $FILE
      }
    }
  }
}
EOF
	cp -vf $i $FILE
done
