#! /bin/sh

# On debian the following commands will setup the require requirements for tpclient-pyogre.

cd ..
# Both libtpproto-py and libtpclient-py need to exist!
if [ ! -x libtpproto-py ]; then
	echo "You do not have libtpproto-py checked out! (which is required!)"
	exit
fi

if [ ! -x libtpclient-py ]; then
	echo "You do not have libtpclient-py checked out! (which is required!)"
	exit
fi

./setup.sh

apt-get install libogre5c2a
apt-get install libogre-dev
apt-get install libcegui-mk2-0c2a
apt-get install libcegui-mk2-dev

apt-get install python-dev

apt-get install subversion
mkdir pyogre
cd pyogre
svn checkout http://svn.berlios.de/svnroot/repos/pyogre/trunk
cd trunk
python setup.py build
python setup.py install

cd ..
cd ..
cd tpclient-pyogre
echo "Ready to go!"
